//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkScript.Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompilerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompilerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VkScript.Parser.CompilerMessages", typeof(CompilerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3001: Невозможно использовать выражения типа &apos;{0}&apos; в качестве значения параметра типа &apos;{1}&apos;!.
        /// </summary>
        internal static string ArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3002: Невозможно добавить объект типа &apos;{0}&apos; в массив типа &apos;{1}&apos;!.
        /// </summary>
        internal static string ArrayElementTypeMismatch {
            get {
                return ResourceManager.GetString("ArrayElementTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3003: Инициализатор массива должен содержать хотя бы один элемент! Для создания пустых массивов воспользуйтесь явным конструктором..
        /// </summary>
        internal static string ArrayEmpty {
            get {
                return ResourceManager.GetString("ArrayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3004: Невозможно использовать выражение типа &apos;{0}&apos; в качестве размера массива, поскольку оно не приводится к System.Int32!.
        /// </summary>
        internal static string ArraySizeNotInt {
            get {
                return ResourceManager.GetString("ArraySizeNotInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3005: Тип массива не может быть выведен! Воспользуйтесь операцией приведения типов..
        /// </summary>
        internal static string ArrayTypeUnknown {
            get {
                return ResourceManager.GetString("ArrayTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3006: Невозможно создать делегат из метода, принимающего более 16 аргументов..
        /// </summary>
        internal static string CallableTooManyArguments {
            get {
                return ResourceManager.GetString("CallableTooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3007: У делегатов &apos;{0}&apos; и &apos;{1}&apos; не совпадают аргументы!.
        /// </summary>
        internal static string CastDelegateArgTypesMismatch {
            get {
                return ResourceManager.GetString("CastDelegateArgTypesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3008: У делегатов &apos;{0}&apos; и &apos;{1}&apos; не совпадают возвращаемые значения: требуется &apos;{2}&apos;, но получено &apos;{3}&apos;!.
        /// </summary>
        internal static string CastDelegateReturnTypesMismatch {
            get {
                return ResourceManager.GetString("CastDelegateReturnTypesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3009: Невозможно привести выражение null к типу &apos;{0}&apos;, поскольку он передается по значению!.
        /// </summary>
        internal static string CastNullValueType {
            get {
                return ResourceManager.GetString("CastNullValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3010: Невозможно привести объект типа &apos;{0}&apos; к типу &apos;{1}&apos;!.
        /// </summary>
        internal static string CastTypesMismatch {
            get {
                return ResourceManager.GetString("CastTypesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3011: Это выражение catch недостижимо, поскольку исключения типа &apos;{0}&apos; будут перехвачены выше как наследники типа &apos;{1}&apos;!.
        /// </summary>
        internal static string CatchClauseUnreachable {
            get {
                return ResourceManager.GetString("CatchClauseUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3012: Тип &apos;{0}&apos; уже был использован в выражении catch текущего блока try!.
        /// </summary>
        internal static string CatchTypeDuplicate {
            get {
                return ResourceManager.GetString("CatchTypeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3013: Тип &apos;{0}&apos; не может быть использован в выражении catch, поскольку он не наследуется от System.Exception!.
        /// </summary>
        internal static string CatchTypeNotException {
            get {
                return ResourceManager.GetString("CatchTypeNotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3014: Невозможно использовать неявную переменную в замыкании!.
        /// </summary>
        internal static string ClosureImplicit {
            get {
                return ResourceManager.GetString("ClosureImplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3015: Невозможно использовать в замыкании аргумент &apos;{0}&apos;, поскольку он передается по ссылке!.
        /// </summary>
        internal static string ClosureRef {
            get {
                return ResourceManager.GetString("ClosureRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3151: Выражение имеет тип &apos;{0}&apos;, который не может принимать значение null!.
        /// </summary>
        internal static string CoalesceOperatorLeftNotNull {
            get {
                return ResourceManager.GetString("CoalesceOperatorLeftNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3152: Тип &apos;{0}&apos; несовместим с типом &apos;{1}&apos;!.
        /// </summary>
        internal static string CoalesceOperatorTypeMismatch {
            get {
                return ResourceManager.GetString("CoalesceOperatorTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3016: Блок кода должен содержать хотя бы одно выражение!.
        /// </summary>
        internal static string CodeBlockEmpty {
            get {
                return ResourceManager.GetString("CodeBlockEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3017: Объявление переменной или константы не может быть последним выражением в блоке!.
        /// </summary>
        internal static string CodeBlockLastVar {
            get {
                return ResourceManager.GetString("CodeBlockLastVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3018: Невозможно определить общий тип для ветвей условия! Типы выражений -  &apos;{0}&apos; и &apos;{1}&apos;..
        /// </summary>
        internal static string ConditionInconsistentTyping {
            get {
                return ResourceManager.GetString("ConditionInconsistentTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3019: Выражение типа &apos;{0}&apos; нельзя использовать в качестве условия, поскольку оно не приводится к типу boolean!.
        /// </summary>
        internal static string ConditionTypeMismatch {
            get {
                return ResourceManager.GetString("ConditionTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3020: Константы нельзя передавать в функции по ссылке!.
        /// </summary>
        internal static string ConstantByRef {
            get {
                return ResourceManager.GetString("ConstantByRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3021: Деление на ноль!.
        /// </summary>
        internal static string ConstantDivisionByZero {
            get {
                return ResourceManager.GetString("ConstantDivisionByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3022: Результат выражения-константы превышает допустимое максимальное значение типа!.
        /// </summary>
        internal static string ConstantOverflow {
            get {
                return ResourceManager.GetString("ConstantOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3023: Конструктор не может быть статическим!.
        /// </summary>
        internal static string ConstructorStatic {
            get {
                return ResourceManager.GetString("ConstructorStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3024: Контекст #{0} не существует!.
        /// </summary>
        internal static string ContextNotFound {
            get {
                return ResourceManager.GetString("ContextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3025: Контекст #{0} был освобожден!.
        /// </summary>
        internal static string ContextUnregistered {
            get {
                return ResourceManager.GetString("ContextUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3026: Вызов делегата типа &apos;{0}&apos; требует {1} аргументов, а передано {2}!.
        /// </summary>
        internal static string DelegateArgumentsCountMismatch {
            get {
                return ResourceManager.GetString("DelegateArgumentsCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3027: Невозможно применить композицию к делегатам типов &apos;{0}&apos; и &apos;{1}&apos;, поскольку их подписи несовместимы!.
        /// </summary>
        internal static string DelegatesNotCombinable {
            get {
                return ResourceManager.GetString("DelegatesNotCombinable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3028: Инициализатор словаря должен содержать хотя бы один элемент! Для создания пустых словарей воспользуйтесь явным конструктором..
        /// </summary>
        internal static string DictionaryEmpty {
            get {
                return ResourceManager.GetString("DictionaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3029: Невозможно добавить ключ типа &apos;{0}&apos; в Dictionary&lt;{1}, {2}&gt;!.
        /// </summary>
        internal static string DictionaryKeyTypeMismatch {
            get {
                return ResourceManager.GetString("DictionaryKeyTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3030: Тип словаря не может быть выведен! Воспользуйтесь операцией приведения типов..
        /// </summary>
        internal static string DictionaryTypeUnknown {
            get {
                return ResourceManager.GetString("DictionaryTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3031: Невозможно добавить значение типа &apos;{0}&apos; в Dictionary&lt;{1}, {2}&gt;!.
        /// </summary>
        internal static string DictionaryValueTypeMismatch {
            get {
                return ResourceManager.GetString("DictionaryValueTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3032: Невозможно получить доступ к &apos;{0}.{1}&apos; из статического контекста!.
        /// </summary>
        internal static string DynamicMemberFromStaticContext {
            get {
                return ResourceManager.GetString("DynamicMemberFromStaticContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3149: Событие не может быть использовано в выражении!.
        /// </summary>
        internal static string EventAsExpr {
            get {
                return ResourceManager.GetString("EventAsExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3033: Выражение типа &apos;{0}&apos; не может быть использовано в блоке &apos;using&apos;, поскольку не приводится к интерфейсу &apos;IDisposable&apos;!.
        /// </summary>
        internal static string ExpressionNotIDisposable {
            get {
                return ResourceManager.GetString("ExpressionNotIDisposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3034: Тип выражения не может быть выведен! Воспользуйтесь операцией приведения типов..
        /// </summary>
        internal static string ExpressionNull {
            get {
                return ResourceManager.GetString("ExpressionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3035: Требуется выражение, возвращающее значение!.
        /// </summary>
        internal static string ExpressionVoid {
            get {
                return ResourceManager.GetString("ExpressionVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3036: Тип &apos;{0}&apos; уже содержит поле &apos;{1}&apos;!.
        /// </summary>
        internal static string FieldRedefinition {
            get {
                return ResourceManager.GetString("FieldRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3037: Тип &apos;{0}&apos; невозможно использовать в качестве границы диапазона, поскольку он не является целочисленным!.
        /// </summary>
        internal static string ForeachRangeNotInteger {
            get {
                return ResourceManager.GetString("ForeachRangeNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3038: Невозможно получить диапазон из выражений типов &apos;{0}&apos; и &apos;{1}&apos;!.
        /// </summary>
        internal static string ForeachRangeTypeMismatch {
            get {
                return ResourceManager.GetString("ForeachRangeTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3039: Найдено несколько подходящих переопределений функции &apos;{0}&apos;! Воспользуйтесь операцией приведения типов для указания конкретного переопределения!.
        /// </summary>
        internal static string FunctionInvocationAmbiguous {
            get {
                return ResourceManager.GetString("FunctionInvocationAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3040: Не найдено ни одного переопределения функции &apos;{0}&apos;, принимающей переданные аргументы!.
        /// </summary>
        internal static string FunctionNotFound {
            get {
                return ResourceManager.GetString("FunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3041: Функция &apos;{0}&apos; с таким списком аргументов уже была объявлена!.
        /// </summary>
        internal static string FunctionRedefinition {
            get {
                return ResourceManager.GetString("FunctionRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3042: Количество обобщенных аргументов не совпадает!.
        /// </summary>
        internal static string GenericArgCountMismatch {
            get {
                return ResourceManager.GetString("GenericArgCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3043: Для обобщенного аргумента &apos;{0}&apos; переданы несовпадающие значения: &apos;{1}&apos; и &apos;{2}&apos;!.
        /// </summary>
        internal static string GenericArgMismatch {
            get {
                return ResourceManager.GetString("GenericArgMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3044: Метод &apos;{0}&apos; не принимает обобщенных аргументов!.
        /// </summary>
        internal static string GenericArgsToNonGenericMethod {
            get {
                return ResourceManager.GetString("GenericArgsToNonGenericMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3045: Значение обобщенного аргумента &apos;{0}&apos; не может быть вычислено!.
        /// </summary>
        internal static string GenericArgumentNotResolved {
            get {
                return ResourceManager.GetString("GenericArgumentNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3046: Тип &apos;{0}&apos; не может быть использован как значение обобщенного аргумента &apos;{1}&apos; для типа &apos;{2}&apos;, поскольку не является ссылочным типом!.
        /// </summary>
        internal static string GenericClassConstraintViolated {
            get {
                return ResourceManager.GetString("GenericClassConstraintViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3047: Тип &apos;{0}&apos; не может быть использован как значение обобщенного аргумента &apos;{1}&apos; для типа &apos;{2}&apos;, поскольку не имеет конструктор по умолчанию!.
        /// </summary>
        internal static string GenericConstructorConstraintViolated {
            get {
                return ResourceManager.GetString("GenericConstructorConstraintViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3048: Для обобщенного аргумента &apos;{0}&apos; был явно указан тип &apos;{1}&apos;, но использование подразумевает тип &apos;{2}&apos;!.
        /// </summary>
        internal static string GenericHintMismatch {
            get {
                return ResourceManager.GetString("GenericHintMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3049: Невозможно вычислить значение обобщенного аргумента &apos;{0}&apos;, используя тип &apos;{1}&apos;!.
        /// </summary>
        internal static string GenericImplementationWrongType {
            get {
                return ResourceManager.GetString("GenericImplementationWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3050: Тип &apos;{0}&apos; не может быть использован как значение обобщенного аргумента &apos;{1}&apos; для типа &apos;{2}&apos;, поскольку не реализует класс или интерфейс &apos;{3}&apos;!.
        /// </summary>
        internal static string GenericInheritanceConstraintViolated {
            get {
                return ResourceManager.GetString("GenericInheritanceConstraintViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3051: Невозможно определить обобщенные аргументы интерфейса &apos;{0}&apos;: тип &apos;{1}&apos; реализует несколько подходящих переопределений!.
        /// </summary>
        internal static string GenericInterfaceMultipleImplementations {
            get {
                return ResourceManager.GetString("GenericInterfaceMultipleImplementations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3052: Тип &apos;{0}&apos; не реализует интерфейс &apos;{1}&apos;!.
        /// </summary>
        internal static string GenericInterfaceNotImplemented {
            get {
                return ResourceManager.GetString("GenericInterfaceNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3053: Обобщенный аргумент &apos;{0}&apos; не был найден!.
        /// </summary>
        internal static string GenericParameterNotFound {
            get {
                return ResourceManager.GetString("GenericParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3054: Тип &apos;{0}&apos; не может быть использован как значение обобщенного аргумента &apos;{1}&apos; для типа &apos;{2}&apos;, поскольку не является передаваемым по значению!.
        /// </summary>
        internal static string GenericStructConstraintViolated {
            get {
                return ResourceManager.GetString("GenericStructConstraintViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3055: Невозможно получить значение глобального свойства &apos;{0}&apos;!.
        /// </summary>
        internal static string GlobalPropertyNoGetter {
            get {
                return ResourceManager.GetString("GlobalPropertyNoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3056: Невозможно задать значение глобального свойства &apos;{0}&apos;!.
        /// </summary>
        internal static string GlobalPropertyNoSetter {
            get {
                return ResourceManager.GetString("GlobalPropertyNoSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3057: Невозможно присвоить глобальному свойству &apos;{0}&apos; значение типа &apos;{1}&apos;! Возможно, требуется явное приведение типа..
        /// </summary>
        internal static string GlobalPropertyTypeMismatch {
            get {
                return ResourceManager.GetString("GlobalPropertyTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3058: &apos;{0}&apos; является константой и изменение ее значения запрещено!.
        /// </summary>
        internal static string IdentifierIsConstant {
            get {
                return ResourceManager.GetString("IdentifierIsConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3059: Переменная или функция без параметров с названием &apos;{0}&apos; не найдена!.
        /// </summary>
        internal static string IdentifierNotFound {
            get {
                return ResourceManager.GetString("IdentifierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3060: Невозможно присвоить значение типа &apos;{0}&apos; переменной типа &apos;{1}&apos;! Возможно. требуется явное приведение типа..
        /// </summary>
        internal static string IdentifierTypeMismatch {
            get {
                return ResourceManager.GetString("IdentifierTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3061: Невозможно неявно привести выражение типа &apos;{0}&apos; к типу &apos;{1}&apos;!.
        /// </summary>
        internal static string ImplicitCastImpossible {
            get {
                return ResourceManager.GetString("ImplicitCastImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3062: Сохраняемые сборки не поддерживают импорт!.
        /// </summary>
        internal static string ImportIntoSaveableAssembly {
            get {
                return ResourceManager.GetString("ImportIntoSaveableAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3063: Только публичные, статические и не содержащие обобщенных аргументов методы могут быть импортированы!.
        /// </summary>
        internal static string ImportUnsupportedMethod {
            get {
                return ResourceManager.GetString("ImportUnsupportedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3064: Индексатор не может быть однозначно определен! Подходят как минимум два переопределения:{3}{0}[{1}]{3}{0}[{2}].
        /// </summary>
        internal static string IndexAmbigious {
            get {
                return ResourceManager.GetString("IndexAmbigious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3065: Нельзя использовать индексатор типа &apos;{0}&apos; в качестве значения для ref-параметра, поскольку возвращаемый им тип &apos;{1}&apos; передается по значению!.
        /// </summary>
        internal static string IndexerValuetypeRef {
            get {
                return ResourceManager.GetString("IndexerValuetypeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3066: Тип &apos;{0}&apos; не содержит индексатора на чтение, который бы принимал индекс типа &apos;{1}&apos;!.
        /// </summary>
        internal static string IndexGetterNotFound {
            get {
                return ResourceManager.GetString("IndexGetterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3067: Тип &apos;{0}&apos; не содержит индексатора на запись, который бы принимал индекс типа &apos;{1}&apos;!.
        /// </summary>
        internal static string IndexSetterNotFound {
            get {
                return ResourceManager.GetString("IndexSetterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3068: Невозможно вычислить значения обобщенных параметров для типа аргумента &apos;{0}&apos;! Укажите тип аргумента явно..
        /// </summary>
        internal static string LambdaArgGenericsUnresolved {
            get {
                return ResourceManager.GetString("LambdaArgGenericsUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3069: Тип аргумента &apos;{0}&apos; не может быть выведен автоматически! Пожалуйста, укажите тип явно!.
        /// </summary>
        internal static string LambdaArgTypeUnknown {
            get {
                return ResourceManager.GetString("LambdaArgTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3150: Делегат ожидает {0} аргументов, но анонимная функция принимает {1}!.
        /// </summary>
        internal static string LambdaArgumentsCountMismatch {
            get {
                return ResourceManager.GetString("LambdaArgumentsCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3070: Анонимная функция используется в качестве делегата типа &apos;{0}&apos;, но ее возвращаемый тип &apos;{1}&apos; несовместим с требуемым возвращаемым типом &apos;{2}&apos;!.
        /// </summary>
        internal static string LambdaReturnTypeMismatch {
            get {
                return ResourceManager.GetString("LambdaReturnTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3071: Возвращаемый тип анонимной функции не может быть выведен! Воспользуйтесь операцией приведения типов..
        /// </summary>
        internal static string LambdaReturnTypeUnknown {
            get {
                return ResourceManager.GetString("LambdaReturnTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3072: Невозможно добавить объект типа &apos;{0}&apos; в List&lt;{1}&gt;!.
        /// </summary>
        internal static string ListElementTypeMismatch {
            get {
                return ResourceManager.GetString("ListElementTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3073: Инициализатор списка должен содержать хотя бы один элемент! Для создания пустых списков воспользуйтесь явным конструктором..
        /// </summary>
        internal static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3074: Тип списка не может быть выведен! Воспользуйтесь операцией приведения типов..
        /// </summary>
        internal static string ListTypeUnknown {
            get {
                return ResourceManager.GetString("ListTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3075: Позиция: {0}.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3076: Позиция: {0} ... {1}.
        /// </summary>
        internal static string LocationSpan {
            get {
                return ResourceManager.GetString("LocationSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3077: Метод &apos;{0}&apos; типа &apos;{1}&apos; с таким списком аргументов уже был объявлен!.
        /// </summary>
        internal static string MethodRedefinition {
            get {
                return ResourceManager.GetString("MethodRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3078: Нельзя использовать метод в качестве значения для ref-параметра!.
        /// </summary>
        internal static string MethodRef {
            get {
                return ResourceManager.GetString("MethodRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3134: Невозможно вывести общий тип для выражений, если хотя бы одно из них имеет тип &apos;Unit&apos; или &apos;Void&apos;!.
        /// </summary>
        internal static string NoCommonType {
            get {
                return ResourceManager.GetString("NoCommonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3051: В типе &apos;{1}&apos; не найдено публичных статических методов с названием &apos;{0}&apos;!.
        /// </summary>
        internal static string NoOverloads {
            get {
                return ResourceManager.GetString("NoOverloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3079: Невозможно применить оператор &apos;{0}&apos; к аргументам типов &apos;{1}&apos; и &apos;{2}&apos;!.
        /// </summary>
        internal static string OperatorBinaryTypesMismatch {
            get {
                return ResourceManager.GetString("OperatorBinaryTypesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3080: Невозможно провести математическую операцию к числам разной знаковости!.
        /// </summary>
        internal static string OperatorTypesSignednessMismatch {
            get {
                return ResourceManager.GetString("OperatorTypesSignednessMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3081: Невозможно применить оператор &apos;{0}&apos; к аргументу типа &apos;{1}&apos;!.
        /// </summary>
        internal static string OperatorUnaryTypeMismatch {
            get {
                return ResourceManager.GetString("OperatorUnaryTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3082: Для вызова конструктора без параметров требуется указать пустые скобки!.
        /// </summary>
        internal static string ParameterlessConstructorParens {
            get {
                return ResourceManager.GetString("ParameterlessConstructorParens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3135: Шаблон массива не может содержать больше одной вложенной последовательности, объявленной с помощью многоточия!.
        /// </summary>
        internal static string PatternArraySubsequences {
            get {
                return ResourceManager.GetString("PatternArraySubsequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3131: Шаблон содержит повторное объявление имени &apos;{0}&apos;!.
        /// </summary>
        internal static string PatternNameDuplicated {
            get {
                return ResourceManager.GetString("PatternNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3132: Некорректное объявление имени в шаблоне: в некоторых альтернативах не объявлено имя &apos;{0}&apos;! Убедитесь, что во всех альтернативах список объявленных имен и их типы в точности совпадают..
        /// </summary>
        internal static string PatternNameSetMismatch {
            get {
                return ResourceManager.GetString("PatternNameSetMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3133: Некорректное объявление имени в шаблоне: типы для имени &apos;{0}&apos; не совпадают в альтернативных шаблонах (например, &apos;{1}&apos; и &apos;{2}&apos;)..
        /// </summary>
        internal static string PatternNameTypeMismatch {
            get {
                return ResourceManager.GetString("PatternNameTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3139: Тип &apos;{0}&apos; должен быть объявлен как запись, чтобы использовать его в данном шаблоне!.
        /// </summary>
        internal static string PatternNotValidRecord {
            get {
                return ResourceManager.GetString("PatternNotValidRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3138: Тип &apos;{0}&apos; должен быть объявлен в скрипте, чтобы использовать его в данном шаблоне!.
        /// </summary>
        internal static string PatternNotValidType {
            get {
                return ResourceManager.GetString("PatternNotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3141: Пределы диапазона должны быть числовыми константами!.
        /// </summary>
        internal static string PatternRangeNotNumeric {
            get {
                return ResourceManager.GetString("PatternRangeNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3143: Повторно указан шаблон для поля &apos;{0}&apos;!.
        /// </summary>
        internal static string PatternRecordFieldDuplicated {
            get {
                return ResourceManager.GetString("PatternRecordFieldDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3140: Запись &apos;{0}&apos; не содержит поля под названием &apos;{1}&apos;!.
        /// </summary>
        internal static string PatternRecordNoField {
            get {
                return ResourceManager.GetString("PatternRecordNoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3142: Вложенная последовательность в IEnumerable должна быть последним элементом шаблона!.
        /// </summary>
        internal static string PatternSubsequenceLocation {
            get {
                return ResourceManager.GetString("PatternSubsequenceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3129: Шаблон кортежа должен содержать хотя бы 1 элемент!.
        /// </summary>
        internal static string PatternTupleTooFewArgs {
            get {
                return ResourceManager.GetString("PatternTupleTooFewArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3128: Шаблон кортежа не может содержать более 7 элементов!.
        /// </summary>
        internal static string PatternTupleTooManyArgs {
            get {
                return ResourceManager.GetString("PatternTupleTooManyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3136: Выражение типа &apos;{0}&apos; никогда не может принимать значения типа &apos;{1}&apos;!.
        /// </summary>
        internal static string PatternTypeMatchImpossible {
            get {
                return ResourceManager.GetString("PatternTypeMatchImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3130: Шаблон не может быть применен к типу &apos;{0}&apos;, поскольку он несовместим с ожидаемым типом &apos;{1}&apos;!.
        /// </summary>
        internal static string PatternTypeMismatch {
            get {
                return ResourceManager.GetString("PatternTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3140: Тип &apos;{0}&apos; не содержит метку!.
        /// </summary>
        internal static string PatternTypeNoTag {
            get {
                return ResourceManager.GetString("PatternTypeNoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3137: Шаблон никогда не будет выполнен, поскольку предыдущий перехватывает все возможные значения!.
        /// </summary>
        internal static string PatternUnreachable {
            get {
                return ResourceManager.GetString("PatternUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3083: Значение свойства #{0} не может быть получено!.
        /// </summary>
        internal static string PropertyIdNoGetter {
            get {
                return ResourceManager.GetString("PropertyIdNoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3084: Значение свойства #{0} не может быть задано!.
        /// </summary>
        internal static string PropertyIdNoSetter {
            get {
                return ResourceManager.GetString("PropertyIdNoSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3085: Свойство #{0} не найдено!.
        /// </summary>
        internal static string PropertyIdNotFound {
            get {
                return ResourceManager.GetString("PropertyIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3086: Свойство &apos;{0}&apos; уже было импортировано!.
        /// </summary>
        internal static string PropertyImported {
            get {
                return ResourceManager.GetString("PropertyImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3087: Значение свойства &apos;{0}.{1}&apos; не может быть получено!.
        /// </summary>
        internal static string PropertyNoGetter {
            get {
                return ResourceManager.GetString("PropertyNoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3088: Значение свойства &apos;{0}.{1}&apos; не может быть задано!.
        /// </summary>
        internal static string PropertyNoSetter {
            get {
                return ResourceManager.GetString("PropertyNoSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3089: Нельзя использовать свойство &apos;{0}.{1}&apos; в качестве значения для ref-параметра, поскольку возвращаемый им тип &apos;{2}&apos; передается по значению!.
        /// </summary>
        internal static string PropertyValuetypeRef {
            get {
                return ResourceManager.GetString("PropertyValuetypeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3090: Функция &apos;{0}&apos; не может быть чистой, поскольку не возвращает значения!.
        /// </summary>
        internal static string PureFunctionReturnUnit {
            get {
                return ResourceManager.GetString("PureFunctionReturnUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3091: Функция &apos;{0}&apos; не может быть чистой, поскольку содержит больше 7 аргументов!.
        /// </summary>
        internal static string PureFunctionTooManyArgs {
            get {
                return ResourceManager.GetString("PureFunctionTooManyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3092: Аргумент {0} требует ссылку типа &apos;{1}&apos;!.
        /// </summary>
        internal static string ReferenceArgExpected {
            get {
                return ResourceManager.GetString("ReferenceArgExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3093: Нельзя использовать ссылку в качестве значения не-ссылочного параметра!.
        /// </summary>
        internal static string ReferenceArgUnexpected {
            get {
                return ResourceManager.GetString("ReferenceArgUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3147: Тип &apos;{0}&apos; не может быть использован в качестве конвертера, поскольку не содержит метода с сигнатурой Parse(string)!.
        /// </summary>
        internal static string RegexConverterTypeIncompatible {
            get {
                return ResourceManager.GetString("RegexConverterTypeIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3146: Тип-конвертер &apos;{0}&apos; не найден!.
        /// </summary>
        internal static string RegexConverterTypeNotFound {
            get {
                return ResourceManager.GetString("RegexConverterTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3145: Дважды использован модификатор &apos;{0}&apos;!.
        /// </summary>
        internal static string RegexDuplicateModifier {
            get {
                return ResourceManager.GetString("RegexDuplicateModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3148: Синтаксическая ошибка в регулярном выражении!.
        /// </summary>
        internal static string RegexSyntaxError {
            get {
                return ResourceManager.GetString("RegexSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3144: Неизвестный модификатор &apos;{0}&apos;!.
        /// </summary>
        internal static string RegexUnknownModifier {
            get {
                return ResourceManager.GetString("RegexUnknownModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3094: Невозможно вызвать функцию &apos;{0}&apos;, поскольку она является зарезервированной!.
        /// </summary>
        internal static string ReservedFunctionInvocation {
            get {
                return ResourceManager.GetString("ReservedFunctionInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3095: Невозможно объявить функцию с именем &apos;{0}&apos;, поскольку она является зарезервированной!.
        /// </summary>
        internal static string ReservedFunctionRedefinition {
            get {
                return ResourceManager.GetString("ReservedFunctionRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3096: Функция типа &apos;{0}&apos; не может вернуть объект типа &apos;{1}&apos;!.
        /// </summary>
        internal static string ReturnTypeMismatch {
            get {
                return ResourceManager.GetString("ReturnTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3097: Настройки безопасного режима не позволяют использовать тип &apos;{0}&apos;!.
        /// </summary>
        internal static string SafeModeIllegalType {
            get {
                return ResourceManager.GetString("SafeModeIllegalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3098: Требуется выражение! Повторный выброс исключения допустим только в выражении catch..
        /// </summary>
        internal static string ThrowArgumentExpected {
            get {
                return ResourceManager.GetString("ThrowArgumentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3099: Тип &apos;{0}&apos; не может быть использован в выражении throw, поскольку он не наследуется от System.Exception!.
        /// </summary>
        internal static string ThrowTypeNotException {
            get {
                return ResourceManager.GetString("ThrowTypeNotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3100: Кортеж должен содержать хотя бы один объект!.
        /// </summary>
        internal static string TupleNoArgs {
            get {
                return ResourceManager.GetString("TupleNoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3101: Кортеж не может содержать больше 8 объектов! Воспользуйтесь структурой или вложенным кортежом..
        /// </summary>
        internal static string TupleTooManyArgs {
            get {
                return ResourceManager.GetString("TupleTooManyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3102: Невозможно создать экземпляр абстрактного типа &apos;{0}&apos;!.
        /// </summary>
        internal static string TypeAbstract {
            get {
                return ResourceManager.GetString("TypeAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3103: Невозможно применить обобщенные параметры к &apos;{0}.{1}&apos;, потому что это не метод!.
        /// </summary>
        internal static string TypeArgumentsForNonMethod {
            get {
                return ResourceManager.GetString("TypeArgumentsForNonMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3104: Тип &apos;{0}&apos; содержит несколько подходящих конструкторов! Воспользуйтесь операцией приведения типов ..
        /// </summary>
        internal static string TypeConstructorAmbiguos {
            get {
                return ResourceManager.GetString("TypeConstructorAmbiguos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3105: Тип &apos;{0}&apos; не содержит конструктор с подходящим списком аргументов!.
        /// </summary>
        internal static string TypeConstructorNotFound {
            get {
                return ResourceManager.GetString("TypeConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3106: Тип &apos;{0}&apos; уже объявлен!.
        /// </summary>
        internal static string TypeDefined {
            get {
                return ResourceManager.GetString("TypeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3107: Тип &apos;{0}&apos; не содержит свойства, метода или поля под названием &apos;{1}&apos;!.
        /// </summary>
        internal static string TypeIdentifierNotFound {
            get {
                return ResourceManager.GetString("TypeIdentifierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3108: Невозможно создать экземпляр интерфейса &apos;{0}&apos;!.
        /// </summary>
        internal static string TypeInterface {
            get {
                return ResourceManager.GetString("TypeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3109: Неоднозначное указание типа: тип &apos;{0}&apos; найден как минимум в двух пространствах имен:{5}{1} в сборке {2}{5}{3} в сборке {4}.
        /// </summary>
        internal static string TypeIsAmbiguous {
            get {
                return ResourceManager.GetString("TypeIsAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3110: Тип &apos;{0}&apos; содержит несколько подходящих переопределений метода &apos;{1}&apos;! Укажите типы аргументов явно..
        /// </summary>
        internal static string TypeMethodAmbiguous {
            get {
                return ResourceManager.GetString("TypeMethodAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3111: Тип &apos;{0}&apos; содержит несколько подходящих переопределений метода &apos;{1}&apos;! Воспользуйтесь операцией приведения типов..
        /// </summary>
        internal static string TypeMethodInvocationAmbiguous {
            get {
                return ResourceManager.GetString("TypeMethodInvocationAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3112: Тип &apos;{0}&apos; не содержит метод &apos;{1}&apos; с подходящим списков аргументов! Соответствующий метод-расширение также не найден..
        /// </summary>
        internal static string TypeMethodNotFound {
            get {
                return ResourceManager.GetString("TypeMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3113: Невозможно передать аргументы выражению типа &apos;{0}&apos;, поскольку он не является функцией!.
        /// </summary>
        internal static string TypeNotCallable {
            get {
                return ResourceManager.GetString("TypeNotCallable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3114: Тип &apos;{0}&apos; не найден!.
        /// </summary>
        internal static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3115: Тип &apos;{0}&apos; нельзя использовать в булевом контексте!.
        /// </summary>
        internal static string TypeNotImplicitlyBoolean {
            get {
                return ResourceManager.GetString("TypeNotImplicitlyBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3116: Тип &apos;{0}&apos; не является перечислимым!.
        /// </summary>
        internal static string TypeNotIterable {
            get {
                return ResourceManager.GetString("TypeNotIterable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3117: Тип &apos;{0}&apos; не является числовым!.
        /// </summary>
        internal static string TypeNotNumeric {
            get {
                return ResourceManager.GetString("TypeNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3118: Тип &apos;{0}&apos; не содержит поля или свойства &apos;{1}&apos;!.
        /// </summary>
        internal static string TypeSettableIdentifierNotFound {
            get {
                return ResourceManager.GetString("TypeSettableIdentifierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3119: Невозможно сравнить объекты типов &apos;{0}&apos; и &apos;{1}&apos;!.
        /// </summary>
        internal static string TypesIncomparable {
            get {
                return ResourceManager.GetString("TypesIncomparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3120: Тип &apos;{0}&apos; не содержит метод &apos;{1}&apos; с подходящим списком аргументов!.
        /// </summary>
        internal static string TypeStaticMethodNotFound {
            get {
                return ResourceManager.GetString("TypeStaticMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3121: Идентификатор &apos;_&apos; является зарезервированным и не может быть использован в названиях переменных, аргументов или любых других объявленных пользователем сущностей!.
        /// </summary>
        internal static string UnderscoreName {
            get {
                return ResourceManager.GetString("UnderscoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3122: Идентификатор &apos;_&apos; не может быть использовать в данном контексте!.
        /// </summary>
        internal static string UnderscoreNameUsed {
            get {
                return ResourceManager.GetString("UnderscoreNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3123: Переменная &apos;{0}&apos; уже объявлена!.
        /// </summary>
        internal static string VariableDefined {
            get {
                return ResourceManager.GetString("VariableDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3124: Переменная &apos;{0}&apos; не объявлена в данной области видимости!.
        /// </summary>
        internal static string VariableNotFound {
            get {
                return ResourceManager.GetString("VariableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3125: Невозможно использовать модификатор &apos;...&apos; в анонимной функции!.
        /// </summary>
        internal static string VariadicArgumentLambda {
            get {
                return ResourceManager.GetString("VariadicArgumentLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3126: Аргумент c модификатором &apos;...&apos; должен быть последним в списке!.
        /// </summary>
        internal static string VariadicArgumentNotLast {
            get {
                return ResourceManager.GetString("VariadicArgumentNotLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE3127: Невозможно создать экземпляр типа Unit или void!.
        /// </summary>
        internal static string VoidTypeDefault {
            get {
                return ResourceManager.GetString("VoidTypeDefault", resourceCulture);
            }
        }
    }
}
